name: CI/CD Build Final

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout Código
      uses: actions/checkout@v4

    - name: Configurar JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Compilar con Maven
      run: mvn clean package -DskipTests

    - name: Organizar archivos para JPackage
      shell: bash
      run: |
        mkdir -p build_input
        # Esto copia el JAR ejecutable sin importar el nombre exacto
        cp target/*.jar build_input/
        # Borramos el original para que jpackage no vea dos archivos
        rm -f build_input/original-*.jar

    - name: Generar Instalador
      shell: bash
      run: |
        # Detectamos el nombre del JAR que quedó
        JAR_NAME=$(ls build_input/*.jar | xargs basename)
        
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          sudo apt-get update && sudo apt-get install -y fakeroot binutils
          jpackage --type deb --dest dist --name "app-pdf-tarea" --input build_input --main-jar "$JAR_NAME" --main-class org.example.tarea_pdf.Launcher --linux-shortcut
        else
          jpackage --type exe --dest dist --name "Instalador_Tarea_PDF" --input build_input --main-jar "$JAR_NAME" --main-class org.example.tarea_pdf.Launcher --win-dir-chooser --win-shortcut
        fi

    - name: Guardar Instaladores
      uses: actions/upload-artifact@v4
      with:
        name: instalador-${{ matrix.os }}
        path: dist/
