name: CI/CD Build Multiplataforma

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Esto permite correrlo manualmente si quieres

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout CÃ³digo
      uses: actions/checkout@v4

    - name: Configurar JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Compilar con Maven (Shaded JAR)
      run: mvn clean package

    - name: Organizar archivos para JPackage
      shell: bash
      run: |
        mkdir -p build_input
        cp target/*-shaded.jar build_input/

    - name: Generar DEB (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update && sudo apt-get install -y fakeroot binutils
        jpackage --type deb --dest dist --name "app-pdf-tarea" --input build_input --main-jar $(basename build_input/*-shaded.jar) --main-class org.example.tarea_pdf.Launcher --linux-shortcut --app-version 1.0.0

    - name: Generar EXE (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        jpackage --type exe --dest dist --name "Instalador_Tarea_PDF" --input build_input --main-jar Tarea_PDF-1.0-SNAPSHOT-shaded.jar --main-class org.example.tarea_pdf.Launcher --win-dir-chooser --win-shortcut

    - name: Guardar Instaladores
      uses: actions/upload-artifact@v4
      with:
        name: instalador-${{ matrix.os }}
        path: dist/
